# Security Definitions for FormulaBlu APIs
# This file contains security schemes and requirements used across all APIs

securitySchemes:
  # API Key Authentication
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
    description: API key for authentication

  # Bearer Token Authentication
  BearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
    description: JWT token for authentication

  # OAuth2 Authentication
  OAuth2:
    type: oauth2
    flows:
      authorizationCode:
        authorizationUrl: https://auth.formulablu.com/oauth/authorize
        tokenUrl: https://auth.formulablu.com/oauth/token
        scopes:
          read: "Read access to FormulaBlu APIs"
          write: "Write access to FormulaBlu APIs"
          admin: "Administrative access to FormulaBlu APIs"

# Global Security Requirements
# These can be overridden at the operation level
security:
  - ApiKeyAuth: []
  - BearerAuth: []
  - OAuth2: [read]
