openapi: 3.0.0
info:
  title: Teams API
  version: 1.0.0
tags: []
paths:
  /api/teams:
    post:
      operationId: createTeam
      description: Create a new team
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          description: Bad Request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity response
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                  - message
                  - errors
                  - timestamp
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationError'
                  timestamp:
                    type: string
                    format: date-time
        '500':
          description: Internal Server Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequest'
  /api/teams/{id}:
    get:
      operationId: getTeam
      description: Get team by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          description: Bad Request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: updateTeam
      description: Update team
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          description: Bad Request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Unprocessable Entity response
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                  - message
                  - errors
                  - timestamp
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationError'
                  timestamp:
                    type: string
                    format: date-time
        '500':
          description: Internal Server Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTeamRequest'
    delete:
      operationId: deleteTeam
      description: Delete team
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: Bad Request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CreateTeamRequest:
      type: object
      description: Create team request
      required:
        - name
        - nationality
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        nationality:
          type: string
          minLength: 2
          maxLength: 3
        foundedYear:
          type: integer
          format: int32
    EntityMetadata:
      type: object
      description: Entity metadata
      required:
        - createdAtTimestamp
        - modifiedAtTimestamp
      properties:
        createdAtTimestamp:
          type: string
          format: date-time
        modifiedAtTimestamp:
          type: string
          format: date-time
    Error:
      type: object
      description: Error response model
      required:
        - code
        - message
        - timestamp
      properties:
        code:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
    Team:
      type: object
      description: Formula 1 Team
      required:
        - id
        - name
        - nationality
        - isActive
        - metadata
      properties:
        id:
          type: string
        name:
          type: string
        nationality:
          type: string
        foundedYear:
          type: integer
          format: int32
        isActive:
          type: boolean
        metadata:
          $ref: '#/components/schemas/EntityMetadata'
    UpdateTeamRequest:
      type: object
      description: Update team request
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        nationality:
          type: string
          minLength: 2
          maxLength: 3
        foundedYear:
          type: integer
          format: int32
        isActive:
          type: boolean
    ValidationError:
      type: object
      description: Validation error details
      required:
        - code
        - message
        - field
      properties:
        code:
          type: string
        message:
          type: string
        field:
          type: string
        rejectedValue:
          type: string
servers:
  - url: http://localhost:8083
    description: Development server
    variables: {}
