name: Build and Release OAS Specifications

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build OAS specifications
              run: npm run build:all

            - name: Validate OpenAPI specifications
              run: |
                  # Install swagger-cli for validation
                  npm install -g @apidevtools/swagger-cli

                  # Validate all generated specs
                  for spec in generated/apis/*.yaml; do
                    echo "Validating $spec..."
                    swagger-cli validate "$spec"
                  done

            - name: Upload generated specifications
              uses: actions/upload-artifact@v4
              with:
                  name: oas-specifications
                  path: generated/apis/
                  retention-days: 30

    release:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build OAS specifications
              run: npm run build:all

            - name: Commit generated specifications
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"

                  # Add generated specs to git
                  git add generated/apis/

                  # Check if there are changes to commit
                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                  else
                    git commit -m "Auto-generated OpenAPI specifications [skip ci]"
                    git push
                  fi

            - name: Create Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ github.run_number }}
                  release_name: OAS Specifications v${{ github.run_number }}
                  body: |
                      Auto-generated OpenAPI specifications from TypeSpec definitions.

                      ## Generated Specifications
                      - drivers-api.yaml

                      ## Usage
                      This release can be used as a Git submodule in the FormulaBlu-API repository.
                  draft: false
                  prerelease: false
